...
......
* [Heeeey, excuse me]
Oh! It's you!
It's been so long since you last spoke to me!
I haven't seen you since you last fell into the trap...
I miss you so much...
Sometimes I can still hear you when I close my eyes...
......